spring:
  application:
    name: faniverse

  datasource:
    url: jdbc:mysql://34.134.108.54:3306/faniverseDB?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: sungshin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  gcp:
    storage:
      credentials:
        location: classpath:handy-curve-428107-k7-6d58aaca3454.json
      project-id: handy-curve-428107-k7

server:
  port: 8080

#Optional: logging level configuration
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE