spring:
  application:
    name: faniverse

  datasource:
    url: jdbc:mysql://localhost:3306/FaniverseDB?useSSL=false&serverTimezone=Asia/Seoul
    username: root

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  gcp:
    storage:
      credentials:
        location: classpath:handy-curve-428107-k7-d31ceda8bee0.json
      project-id: handy-curve-428107-k7
      bucket: faniverse-bucket

server:
  port: 8080

#Optional: logging level configuration
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE